login_check:
    path:     /api/login_check
    methods:  [POST]
    defaults:
        _format: json

homepage:
    path: /
    controller: App\Controller\HomeController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
